#!/usr/bin/env python3
"""gen_keycodes.py -- extrae los KC_* / QK_* de QMK y genera un header C.

Filosofía LangSec: source of truth vive en QMK upstream (quantum/keycodes.h).
Este script lo parsea y emite src/keycodes_generated.h con una tabla estática
que el lexer usa para resolver identifiers como `KC_R`, `KC_LSFT`, `QK_KB_0`
a sus valores numéricos.

Cuando QMK upstream añade keycodes nuevos, se re-corre este script y ya.
Copiado del pattern que ANTI usa en su parser DICOM (tags extraídos del
HTML del standard, generación una vez, olvidas la tabla existe).

Usage: python3 tools/gen_keycodes.py [/path/to/vial-qmk]
       (default: ~/vial-qmk)
"""
import os
import re
import sys

DEFAULT_QMK = os.path.expanduser("~/vial-qmk")
SRC_FILE   = "quantum/keycodes.h"
OUT_FILE   = "src/keycodes_generated.h"

# Match `    KC_FOO = 0x1234,` OR `    KC_BAR = KC_FOO,` (ambos aliases)
LITERAL_RE = re.compile(r'^\s*([A-Z][A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+)\s*,?\s*$')
ALIAS_RE   = re.compile(r'^\s*([A-Z][A-Z0-9_]+)\s*=\s*([A-Z][A-Z0-9_]+)\s*,?\s*$')

def parse_qmk(path):
    """Returns dict {name: int_value} resolving aliases transitively."""
    literals = {}   # direct hex values
    aliases  = {}   # name -> other_name (unresolved)
    with open(path) as f:
        for line in f:
            m = LITERAL_RE.match(line)
            if m:
                literals[m.group(1)] = int(m.group(2), 16)
                continue
            m = ALIAS_RE.match(line)
            if m:
                aliases[m.group(1)] = m.group(2)
    # Resolve aliases (bounded chain: max 10 hops to avoid cycles)
    resolved = dict(literals)
    for name, target in aliases.items():
        cur = target
        for _ in range(10):
            if cur in literals:
                resolved[name] = literals[cur]
                break
            if cur in aliases:
                cur = aliases[cur]
                continue
            break  # unresolvable
    return resolved

def emit_header(entries, out_path):
    """Write C header with static table + linear-search lookup."""
    # Sort alfabéticamente para grep-abilidad. Linear search en ~800 entries
    # es ~microsegundos -- compile-time, cero impacto.
    items = sorted(entries.items())
    lines = [
        "// AUTO-GENERATED by tools/gen_keycodes.py from vial-qmk/quantum/keycodes.h",
        "// DO NOT EDIT MANUALLY. Regenerate with: make regen-keycodes",
        "//",
        f"// Source: {SRC_FILE}",
        f"// Entries: {len(items)} keycodes (literales + alias resueltos)",
        "#pragma once",
        "#include <stdint.h>",
        "#include <string.h>",
        "",
        "typedef struct { const char *name; uint16_t value; } qks_keycode_t;",
        "",
        f"static const qks_keycode_t qks_keycodes[] = {{",
    ]
    for name, val in items:
        lines.append(f'    {{"{name}", 0x{val:04X}}},')
    lines.append("};")
    lines.append(f"static const size_t qks_keycodes_n = sizeof(qks_keycodes)/sizeof(qks_keycodes[0]);")
    lines.append("")
    lines.append("// Lookup por name. Retorna value en [0..0xFFFF], o -1 si no existe.")
    lines.append("// Linear scan sobre ~800 entries. Compile-time, cero impacto runtime.")
    lines.append("static inline int32_t qks_lookup_keycode(const char *name) {")
    lines.append("    for (size_t i = 0; i < qks_keycodes_n; i++) {")
    lines.append("        if (strcmp(qks_keycodes[i].name, name) == 0)")
    lines.append("            return (int32_t)qks_keycodes[i].value;")
    lines.append("    }")
    lines.append("    return -1;")
    lines.append("}")
    with open(out_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"wrote {out_path}: {len(items)} keycodes")

def main():
    qmk_root = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_QMK
    src = os.path.join(qmk_root, SRC_FILE)
    if not os.path.exists(src):
        sys.exit(f"error: {src} no existe. usage: {sys.argv[0]} [vial-qmk-path]")
    entries = parse_qmk(src)
    if not entries:
        sys.exit(f"error: no encontré keycodes en {src}")
    emit_header(entries, OUT_FILE)

if __name__ == "__main__":
    main()
